# Generated by Django 4.1.3 on 2022-12-20 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Entrepreneur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("compname", models.CharField(max_length=255)),
                ("password", models.CharField(max_length=255)),
                ("category", models.CharField(max_length=255)),
                ("phone", models.CharField(max_length=255)),
                ("email", models.CharField(max_length=255)),
                ("address", models.CharField(max_length=255)),
                ("description", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("name_eng", models.CharField(max_length=255)),
                ("birth_day", models.CharField(max_length=255)),
                ("sex", models.CharField(max_length=255)),
                ("nationality", models.CharField(max_length=255)),
                ("religion", models.CharField(max_length=255)),
                ("phone", models.CharField(max_length=255)),
                ("email", models.CharField(max_length=255)),
                ("grade", models.CharField(max_length=255)),
                ("school", models.CharField(max_length=255)),
                ("faculty", models.CharField(max_length=255)),
                ("major", models.CharField(max_length=255)),
                ("education_category", models.CharField(max_length=255)),
                ("state", models.CharField(max_length=255)),
                ("year", models.CharField(max_length=255)),
                ("gpa", models.CharField(max_length=255)),
                (
                    "application_form",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="home.entrepreneur",
                    ),
                ),
            ],
        ),
    ]
